### PR TITLE
Use transparent background for sponsor's rect

### PR DESCRIPTION
**Pull request by MaxGraey**
It's especially important for dark mode

### CODE REVIEW

**Comment by dcodeIO** [comment]
The idea is that sponsor logos should not flip their background, since many companies have designs for both and don't like seeing these mixed. That's why the background is always white.

**Comment by MaxGraey** [comment]
Yeah, I see. But many logos designed to look normally on light and dark background normally. That's pretty much how it is. You only need to invert texts:
night

 I think we could create two variants of this logos. For dark and light bg

**Comment by MaxGraey** [comment]
https://twitter.com/ashtom/status/1463554157932023808

https://user-images.githubusercontent.com/1301959/143285438-e154b0cf-46ba-4c66-8c1e-e0c52b9780f2.mp4

**Comment by dcodeIO** [comment]
Looking at this again, I think what we'd at least need to make different backgrounds feasible is logos for both light and dark backgrounds, for every logo displayed. Otherwise we are at risk to violate branding guidelines. The only alternative I could think of is to use grayscale and on dark backgrounds invert, but that's still a, heh, gray area.

**Pull request closed without merging**
